/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/editedComputer.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/editedComputer.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[2.052, 0.369, 1.048]} rotation={[-Math.PI / 2, 0, 0]} scale={33.72}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 0.171, 0]}>
            <mesh geometry={nodes.pCube94_corpo_do_teclado_0.geometry} material={materials.corpo_do_teclado} />
            <mesh geometry={nodes.pCube94_teclado_0.geometry} material={materials.teclado} />
          </group>
          <group position={[11.764, 0.189, -0.483]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.pCylinder2_mouse_0.geometry} material={materials.mouse} />
            <mesh geometry={nodes.pCylinder2_scroll_0.geometry} material={materials.scroll} />
          </group>
          <group position={[-0.023, 3.798, -4.878]} rotation={[-Math.PI, 0, -Math.PI]} scale={[9.223, 4.632, 0.268]}>
            <mesh geometry={nodes.tvpCube1_tvcorpo2_tv_0.geometry} material={materials.tvcorpo2_tv} />
            <mesh geometry={nodes.tvpCube1_tvcorpo_da_tv_0.geometry} material={materials.tvcorpo_da_tv} />
            <mesh geometry={nodes.tvpCube1_tvpes_da_tv1_0.geometry} material={materials.tvpes_da_tv1} />
            <mesh geometry={nodes.tvpCube1_tvtela_da_tv_0.geometry} material={materials.tvtela_da_tv} position={[0.001, 0.002, -0.102]} />
          </group>
        </group>
      </group>
      <mesh geometry={nodes.LinkedinSS.geometry} material={materials.LinkedinSS} position={[2.039, 1.652, -0.548]} rotation={[Math.PI / 2, 0, 0]} scale={[1.575, 1.129, 1.524]} />
    </group>
  )
}

useGLTF.preload('/editedComputer.gltf')
